name: Bulid and deploy ECR AND Lambda
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
    build:
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2
        - name: Set up python
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'
          
        - name: Create and start virtual environment
          run: |
            python -m venv venv
            source venv/bin/activate
            
        - name: Install dependencies
          run: pip install -r requirements.txt

    AWS_ECR:
          needs: [build]
          runs-on: ubuntu-latest
          steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1


            - name: Log into AWS ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: build, tag, and push image to Amazon ECR
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry}}
                ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY}}
                IMAGE_TAG: ${{github.sha}}-latest
              run: |
                docker  build -t $ECR_REGISTRY/$AWS_ECR_REPOSITORY:$IMAGE_TAG .
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

            - name: Log out of AWS ECR
              if: always()
              run: docker logout ${{steps.login-ecr.outputs.registry}}
